/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#001e41',
        'surface-container': '#ebeef0',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#9ccaff',
        'on-tertiary-fixed': '#022020',
        outline: '#74777f',
        'secondary-container': '#46a8fe',
        'surface-tint': '#3a5f94',
        'tertiary-fixed': '#cae8e8',
        'surface-container-low': '#f1f4f6',
        'on-surface': '#181c1e',
        tertiary: '#000708',
        'error-container': '#ffdad6',
        'surface-bright': '#f7fafc',
        'secondary-fixed': '#d0e4ff',
        'on-secondary-fixed': '#001d35',
        'on-primary-fixed': '#001b3c',
        'primary-fixed': '#d5e3ff',
        surface: '#f7fafc',
        'on-surface-variant': '#43474e',
        'surface-dim': '#d7dadc',
        'surface-container-high': '#e5e9eb',
        'inverse-surface': '#2d3133',
        primary: '#000614',
        'on-secondary-container': '#003c65',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        background: '#f7fafc',
        'on-primary-container': '#6487bf',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#304b4c',
        'on-secondary-fixed-variant': '#00497a',
        'inverse-primary': '#a7c8ff',
        'tertiary-container': '#042324',
        'on-background': '#181c1e',
        'on-primary-fixed-variant': '#1f477b',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#aecccc',
        'surface-variant': '#e0e3e5',
        secondary: '#0062a1',
        'inverse-on-surface': '#eef1f3',
        'on-tertiary-container': '#6f8c8c',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#a7c8ff',
        'outline-variant': '#c4c6cf',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      fontFamily: {
        headline: ['"Public Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
